# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenedor', '0012_producto_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.IntegerField(default=0)),
                ('valor_unidad', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('compraproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra.CompraProducto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.Producto')),
            ],
        ),
    ]
