# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraproducto',
            name='factura',
            field=models.IntegerField(default=0),
        ),
    ]
