# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=70)),
                ('rsocial', models.CharField(max_length=200)),
                ('giro', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=70)),
                ('contacto', models.CharField(max_length=70, null=True)),
                ('email', models.EmailField(max_length=70, null=True)),
                ('telefono', models.CharField(max_length=70, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('cargo', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=70)),
                ('rsocial', models.CharField(max_length=70)),
                ('giro', models.CharField(max_length=70)),
                ('direccion', models.CharField(max_length=70)),
                ('comuna', models.CharField(max_length=70)),
                ('telefono', models.CharField(max_length=70)),
                ('nombre', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('contactos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.Contacto')),
            ],
        ),
    ]
