# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='tipo',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
