# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0002_contacto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='tipo',
            field=models.CharField(max_length=70),
        ),
    ]
