# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0005_auto_20171102_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='valor',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='web',
            field=models.URLField(),
        ),
    ]
