# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0006_auto_20171102_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='web',
            field=models.URLField(default='www.sitio.cl'),
        ),
    ]
