# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 12:07
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0007_auto_20171102_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descuento',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3),
        ),
        migrations.AlterField(
            model_name='producto',
            name='valor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='web',
            field=models.URLField(default='http://www.sitio.cl'),
        ),
    ]
