# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0010_auto_20171103_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
    ]
