# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenedor', '0012_producto_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.IntegerField(default=0)),
                ('valor_unidad', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='itemventa',
            name='ventaproducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.VentaProducto'),
        ),
    ]
